/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        canvas: 'var(--canvas)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        raised: 'var(--raised)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        'border-hard': 'var(--border-hard)',
        'text-1': 'var(--text-1)',
        'text-2': 'var(--text-2)',
        'text-3': 'var(--text-3)',
        'text-inv': 'var(--text-inv)',
        accent: 'var(--accent)',
        'accent-dim': 'var(--accent-dim)',
        'accent-fg': 'var(--accent-fg)',
        green: 'var(--green)',
        amber: 'var(--amber)',
        red: 'var(--red)',
        violet: 'var(--violet)',
        cyan: 'var(--cyan)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'system-ui', 'sans-serif'],
        mono: ['Space Mono', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        '2xs': ['11px', '16px'],
        xs: ['12px', '18px'],
        sm: ['13px', '20px'],
        base: ['15px', '24px'],
        md: ['16px', '26px'],
        lg: ['18px', '28px'],
        xl: ['20px', '30px'],
        '2xl': ['24px', '34px'],
        '3xl': ['30px', '38px'],
        '4xl': ['38px', '46px'],
        '5xl': ['52px', '60px'],
        '6xl': ['68px', '76px'],
        '7xl': ['88px', '96px'],
        '8xl': ['112px', '116px'],
      },
      letterSpacing: {
        tightest: '-0.06em',
        tighter: '-0.04em',
        tight: '-0.025em',
        snug: '-0.015em',
        normal: '0em',
        wide: '0.04em',
        wider: '0.08em',
        widest: '0.14em',
      },
      borderRadius: {
        sm: '6px',
        DEFAULT: '10px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '32px',
      },
      boxShadow: {
        'nb-sm': '3px 3px 0 var(--border-hard)',
        nb: '4px 4px 0 var(--border-hard)',
        'nb-md': '5px 5px 0 var(--border-hard)',
        'nb-lg': '6px 6px 0 var(--border-hard)',
        'nb-xl': '8px 8px 0 var(--border-hard)',
        'nb-accent': '4px 4px 0 #FFE600',
        'nb-black': '4px 4px 0 #000000',
        card: '0 4px 24px rgba(0,0,0,0.08)',
        'card-dark': '0 4px 24px rgba(0,0,0,0.4)',
        'glow-accent': '0 0 32px rgba(255,230,0,0.2)',
      },
      animation: {
        'fade-up': 'fadeUp 0.5s cubic-bezier(0.16,1,0.3,1) both',
        'fade-in': 'fadeIn 0.4s ease both',
        float: 'float 8s ease-in-out infinite',
        'pulse-dot': 'pulse-dot 2.4s ease-in-out infinite',
        shimmer: 'shimmer 2s linear infinite',
        'spin-slow': 'spin-slow 8s linear infinite',
        beam: 'beam-travel 2.4s ease-in-out infinite',
        ticker: 'ticker 28s linear infinite',
        scan: 'scan-line 3s linear infinite',
        blink: 'blink 1.2s step-end infinite',
        'count-up': 'count-up 0.5s cubic-bezier(0.16,1,0.3,1) both',
      },
      keyframes: {
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        float: {
          '0%,100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'pulse-dot': {
          '0%,100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.5', transform: 'scale(0.85)' },
        },
        shimmer: {
          from: { backgroundPosition: '-200% 0' },
          to: { backgroundPosition: '200% 0' },
        },
        'beam-travel': {
          '0%': { transform: 'translateX(-120%)', opacity: '0' },
          '15%': { opacity: '1' },
          '85%': { opacity: '1' },
          '100%': { transform: 'translateX(320%)', opacity: '0' },
        },
        'scan-line': {
          '0%': { top: '-4px' },
          '100%': { top: '100%' },
        },
        ticker: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        blink: {
          '0%,100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        'count-up': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34,1.56,0.64,1)',
        'out-expo': 'cubic-bezier(0.16,1,0.3,1)',
        'in-expo': 'cubic-bezier(0.7,0,0.84,0)',
      },
    },
  },
  plugins: [],
}
